default:
  setting_yml_path: 'config/application.yml'
  route:
    not_found_to: 'base#not_found'
  db_dump:
    enable: true
    s3:
      enable: true
  db_backup:
    enable: true
    s3_bucket: "<%= ENV['APP_NAME'] %>-backup"
    exclude_tables:
      -
  imager:
    enable: true
  model:
    enables:
      enum: true
      tree: true
      enabled: true
      array_order: true
      attr_json: true
      jsonb_property: false
      address: false
      variables: false
      sn: false
  for_text_search:
    enable: true
  notification:
    enable: true
    class_name: Notification
  rack:
    middlewares:
      cloudflare:
        enable: false
      utf8_sanitizer:
        enable: true
  aws:
    enable: true
    ses:
      enable: true
      auto_blacklist: true
      notification_emails:
        - hi@5fpro.com
    s3:
      enable: false # 目前沒有影響
  omniauth:
    enable: true
    resource: user
    providers:
      facebook:
        enable: true
      github:
        enable: false
      google_oauth2:
        enable: true
  linebot:
    enable: false
  revision:
    enable: <%= Rails.env.production? ? false : true %>
  seo_robots:
    enable: true
  sitemap:
    enable: true
    sites:
      default:
        ping_search_engines: true
        cloudfront_id:
        cloudfront_invalidation: /sitemaps/*
  comments:
    enable: false
  sidekiq:
    enable: true
  sidekiq_scheduler:
    enable: true
  tappay:
    enable: false
  devise:
    enable: true
    mailer_view_path: 'tyr/users/mailer'
    layouts:
      user: tyr_admin_landing
      administrator: tyr_admin_landing
  devise_async:
    enable: true
  meta_tags:
    enable: true
  mfa:
    enable: true
  admin:
    enable: true
    enable_mfa: true
    enable_permission: true
    enable_my_link: true
    administrator_class_name: 'Administrator'
    assets:
      cdn_host: 'assets.5fpro.com'
    notifications:
      enable: true
  permission:
    enable: true
  asset_sync:
    enable: true
    fog_public: false
  asset_host:
    enable: true
  carrierwave:
    enable: true
    fog_public: false
    # distribution_id: "<%= ENV['CARRIERWAVE_DISTRIBUTION_ID'] %>"
    tinypng:
      enable: false
    cloudconvert:
      enable: true
  locale:
    enable: true
    default: zh-TW
    available:
      - en
      - zh-TW
  lograge:
    enable: true
  api:
    enable: true
  mailer:
    enable: true
    enable_blacklist: true
    notification_email: 'noreply@5fpro.com'
    layout: mailer
  staging_authorize:
    enable: true
  redis:
    enable: true
  rollbar:
    enable: true
  paper_trail:
    enable: true
  dalli:
    enable: true
  event_log:
    enable: true
    class_name: 'EventLog'
  post_redirect:
    enable: true
  transaction_log:
    enable: false
  attachment:
    enable: true
    uploader: 'AttachmentUploader'
    class_name: 'Attachment'
    enable_admin: true
    custom_uploader:
      enable: true
      enable_admin: true
      uploaders:
        default:
          name: 一般縮圖
          versions:
            thumb:
              process:
                resize_to_fill:
                  - 300
                  - 300
            thumb_2x:
              process:
                resize_and_pad:
                  - 600
                  - 600
            small:
              process:
                resize_to_limit:
                  - 400
                  - 400
            small_2x:
              process:
                resize_to_limit:
                  - 800
                  - 800
            cloudconvert_small_2x:
              process:
                resize_to_limit:
                  - 800
                  - 800
                to_cloudconvert:
                  - webp
          render:
            img:
              src: small_2x
              sizes: '(max-width: 500px) 90vw, 60vw'
              srcset:
                500w: small
                1000w: small_2x
            # ----- or -------
            # picture:
            #   -
            #     media: "(min-width: 650px)"
            #     srcset:
            #       1x: samll
            #       2x: samll_2x
            #   -
            #     media: "(min-width: 465px)"
            #     srcset:
            #       1x: small
            #       2x: small_2x
            #   -
            #     src: small_2x

  renderers:
    enable: true
  sortable:
    enable: true
  restorable:
    enable: false
  taggable:
    enable: true
  ransackable:
    enable: true
  charts:
    enable: true
  phonelib:
    enable: true
  activity:
    enable: true
    class_name: Activity
  preview:
    enable: true
  page_block:
    enable: true
    class_name: 'PageBlock'
    blocks:
      default:
        label: 預設區塊
        preview_url: /
        body_input: redactorx
        helpers:
          - Tyr::UtilitHelper
  article:
    enable: true
    enable_restore: false
    enable_category: true
    default_class_name: 'Article'
    default_category_class_name: 'ArticleCategory'
    default_cover_class_name: ImageAttachment
    default_image_class_name: ImageAttachment
    default_attachment_class_name: Attachment
    layouts:
      default:
        category_max_deeps: 1
        article_class_name: Article
        category_class_name: ArticleCategory
      blog:
        article_class_name: Article
        category_class_name: ArticleCategory
    admin:
      enable: true
  pageview:
    enable: true
    geodecode:
      enable: false
      ipstack_api_key:
    default_class_name: Tyr::Pageview
    scopes:
      - default
    admin:
      enable: true
  line_item:
    enable: false
  cart:
    enable: false
  app_setting:
    enable: true
    class_name: AppSetting
    storage_class_name: AppSettingStorage
    admin:
      enable: true
      form_view_path: admin/settings/form
  webpage:
    enable: true
    enable_route: true
    enable_web_schema: true
  form_select:
    enable: true
    layouts:
      users:
        class_name: User
        search_attributes:
          - name
          - email
  edm:
    enable: false
  recaptcha:
    enable: true
  cvs_selector:
    enable: false
  background_task:
    enable: true
    admin:
      enable: true
  amoeba:
    enable: true
    admin:
      enable: true
  catalog:
    enable: true
  telegram:
    enable: true
  onetime:
    enable: true
  redactor:
    enable: false
  imperavi:
    enable: true
  codemirror:
    enable: true
  mylist:
    enable: true
  web_schema:
    enable: true
  numero:
    enable: true
    admin:
      enable: true

